name: mobile_hr
description: Mobile HR.


publish_to: 'none' # Remove this line if you wish to publish to pub.devReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  flutter_hooks: ^0.18.2
  cloud_firestore: ^3.1.5
  firebase_core: ^1.10.6
  firebase_auth: ^3.3.4
  firebase_storage: ^10.0.5
  file_picker: ^4.3.0
  open_file: ^3.2.1
  font_awesome_flutter: ^9.2.0
  line_icons: ^2.0.1
  google_fonts: ^2.1.1
  iconly: ^1.0.1
  intl: ^0.17.0
  provider: ^6.0.1
  google_sign_in: ^5.1.1
  page_view_indicators: ^2.0.0
  syncfusion_flutter_sliders: ^19.4.38
  flutter_advanced_drawer: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0

flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  #   - images/a_dot_ham.jpeg

